DROP TABLE IF EXISTS "load_event";

CREATE TABLE "load_event"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "load_id"     bigint,
    "customer_id" bigint,
    "load_amount" double precision,
    "status" varchar(255),
    "accepted"    boolean,
    "time"        timestamptz
);
